#!/bin/bash

exit_on_fail() {
    if ! [ $? -eq 0 ]; then
        exit 1
    fi
}

BUILD_DIR="./build"
PROJECT_PATH=$(pwd)
EXECUTABLE="memo_server 127.0.0.1 8000 $PROJECT_PATH"
RUN_REQUESTED=0
SKIP_BUILD=0

for arg in "$@"
do
    if   [ $arg = '-r' ]; then
        RUN_REQUESTED=1

    elif [ $arg = '-s' ]; then
        SKIP_BUILD=1
    fi
done

cd $BUILD_DIR
exit_on_fail

if [ "$SKIP_BUILD" -eq "0" ]; then
    echo "++ Building project"
    echo "*******************************"
    make -j4
    exit_on_fail
    echo "*******************************"
    echo "++ Build successfull"
    echo ""
else
    echo "++ Skipping build (requested)"
fi

if [ "$RUN_REQUESTED" -eq "1" ]; then
    echo "++ Running program..."
    ./$EXECUTABLE
fi

