#!/bin/bash

exit_on_fail() {
    if ! [ $? -eq 0 ]; then
        exit 1
    fi
}

BUILD_DIR="./build"
PROJECT_PATH=$(pwd)
EXECUTABLE="memo_server 127.0.0.1 8000 $PROJECT_PATH"

cd $BUILD_DIR
exit_on_fail

echo "++ Building project"
echo "*******************************"
make -j4
exit_on_fail

echo "*******************************"
echo "++ Build successfull"
echo ""
echo "++ Running program..."
./$EXECUTABLE

